Repository ReDI-School/S25-Full-Stack-Circle, pull requests merged in 2025-04, with the labels that each got.

#82 reset and normalize css and ....
  index.html
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/index.css
  src/pages/ExploreDetailpage.jsx
  src/pages/Explorepage.jsx
  src/pages/Homepage.jsx
Labels: enhancement

#89 Made ExplorePage BestofPinterest Section with css
  src/App.jsx
  src/components/ExplorePage_Best_Of_Pinterest_Section.jsx
  src/pages/Explorepage.jsx
Labels: enhancement

#80 Implemented Popular Ideas section for the explorepage
  src/assets/data.json
  src/components/PopularSearchSection/PopularSearchBtn.jsx
  src/components/PopularSearchSection/PopularSearchList.jsx
Labels: enhancement

#112 96 create shop item component
  src/App.jsx
  src/pages/ImageDetailPage.jsx
  src/pages/ImageDetailPage/ShopItem.css
  src/pages/ImageDetailPage/ShopItem.jsx
Labels: Explore Detail Page

#114 94 add breadcrumb component
  src/pages/ImageDetailPage.jsx
  src/pages/ImageDetailPage/Breadcrumb.css
  src/pages/ImageDetailPage/Breadcrumb.jsx
Labels: enhancement

#91 Add header detail to the explorer detail page
  src/components/PinDetailComponent.jsx
Labels: enhancement

#134 Name add to contributor's list
  README.md
Labels: documentation

#135 See more button
  src/components/ExplorePage_Best_Of_Pinterest_Section.jsx
  src/components/SeeMoreButton.jsx
  src/components/SeeMoreButton.module.css
Labels: Explore Page

#136 addtion of Profile popup and Save Button
  src/pages/ImageDetailPage.jsx
  src/pages/ImageDetailPage/Breadcrumb.css
  src/pages/ImageDetailPage/ShopItem.css
  src/pages/ImageDetailPage/ShopItem.jsx
  src/pages/ImageDetailPage/ShopItem.module.css
Labels: enhancement

#113 Create login form
  package-lock.json
  package.json
  public/images/facebook-2020-2-1.svg
  public/images/google-new.svg
  public/images/pinterest-3.svg
  src/App.jsx
  src/components/Forms/Login/Login.jsx
  src/components/Forms/Login/Login.module.css
  src/components/Forms/SignUp/SignUp.jsx
  src/components/Forms/SignUp/SignUp.module.css
  src/components/Header/Header.jsx
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.module.css
  src/components/Modal/hooks/useModal.jsx
  src/components/Navbar/navbar.jsx
  src/main.jsx
Labels: Home Page

#138 initial commit for OptionsList
  src/components/OptionsList/OptionsList.jsx
  src/components/OptionsList/OptionsList.module.css
  src/components/OptionsList/OptionsListItem.jsx
  src/components/OptionsList/OptionsListItem.module.css
Labels: Explore Detail Page

#120 DetailPage_buttons
  src/components/Buttons/DetailButtons.jsx
  src/components/Buttons/DetailButtons.module.css
Labels: Explore Detail Page

#129 add guidelines for css
  src/CSS_Guidelines.md
Labels: documentation

#153 Integrated PinDetail component
  frontend/src/components/PinDetailComponent.jsx
  frontend/src/components/pinDetail.module.css
  frontend/src/pages/ImageDetailPage/ShopItem.jsx
Labels: Explore Detail Page

#173 Feature/reactions endpoit
  backend/.env.text
  backend/.gitignore
  backend/package.json
  backend/postman/reactions.postman_collection.json
  backend/prisma/migrations/20250425150532_init/migration.sql
  backend/prisma/migrations/migration_lock.toml
  backend/prisma/schema.prisma
  backend/prisma/seeds.js
  backend/src/constants/http.js
  backend/src/controllers/reactionsController.js
  backend/src/index.js
  backend/src/prisma/client.js
  backend/src/routes/reactionsRoute.js
  eslint.config.js
  package-lock.json
Labels: backend
